/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import View.QLNLView;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
/**
 *
 * @author anhtu
 */
public class HomePage extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form HomePage
     */
   
    public HomePage() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        MainMenu.initMoving(HomePage.this);
        bttQLMA.addActionListener(this);
        bttQLNL.addActionListener(this);
        bttQLNV.addActionListener(this);
        bttQLSA.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel1 = new View.Palette.HomePanel();
        jPanel1 = new javax.swing.JPanel();
        bttQLMA = new javax.swing.JButton();
        bttQLNL = new javax.swing.JButton();
        bttQLNV = new javax.swing.JButton();
        bttQLSA = new javax.swing.JButton();
        MainMenu = new View.Palette.MenuPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang Chủ");
        setUndecorated(true);

        homePanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new java.awt.GridLayout(0, 4));

        bttQLMA.setBackground(new java.awt.Color(255, 153, 153));
        bttQLMA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bttQLMA.setText("Quản Lý Món Ăn");
        jPanel1.add(bttQLMA);

        bttQLNL.setBackground(new java.awt.Color(255, 204, 204));
        bttQLNL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bttQLNL.setText("Quản Lý Nguyên Liệu");
        jPanel1.add(bttQLNL);

        bttQLNV.setBackground(new java.awt.Color(255, 255, 204));
        bttQLNV.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bttQLNV.setText("Quản Lý Nhân Viên");
        jPanel1.add(bttQLNV);

        bttQLSA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bttQLSA.setText("Quản Lý Suất Ăn");
        bttQLSA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(bttQLSA);

        javax.swing.GroupLayout homePanel1Layout = new javax.swing.GroupLayout(homePanel1);
        homePanel1.setLayout(homePanel1Layout);
        homePanel1Layout.setHorizontalGroup(
            homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        homePanel1Layout.setVerticalGroup(
            homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanel1Layout.createSequentialGroup()
                .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 460, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HomePage().setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.Palette.MenuPanel MainMenu;
    private javax.swing.JButton bttQLMA;
    private javax.swing.JButton bttQLNL;
    private javax.swing.JButton bttQLNV;
    private javax.swing.JButton bttQLSA;
    private View.Palette.HomePanel homePanel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Events
     */
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(bttQLSA)){
            bttQLSAClick();
        }else if(e.getSource().equals(bttQLMA)){
            bttQLMAClick();
        }else if(e.getSource().equals(bttQLNL)){
            bttQLNLClick();
        }else{
            bttQLNVClick();
        }
    }
    
    public void bttQLSAClick(){
        new QLSuatAnView().setVisible(true);
        this.dispose();
    }
    
    public void bttQLMAClick(){
        new QLMonAnView().setVisible(true);
        this.dispose();
    }
    
    public void bttQLNLClick(){
        new QLNLView().setVisible(true);
        this.dispose();
    }
    
    public void bttQLNVClick(){
        new QLNhanVienView().setVisible(true);
        this.dispose();
    }
}
