/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MonAnDAO;
import Model.MonAn;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author anhtu
 */
public class QLMonAnView extends javax.swing.JFrame implements ActionListener {
    private MonAn monAn;
    private ArrayList<MonAn> list = new MonAnDAO().getListMA();
    /**
     * Creates new form QLMonAnView
     */
    public QLMonAnView() {
        initComponents();
        btt_Nhap.addActionListener(this);
        dialogbtt_Nhap.addActionListener(this);
        btt_Sua.addActionListener(this);
        dialogbtt_Sua.addActionListener(this);
        btt_Xoa.addActionListener(this);
        dialogbtt_Xoa.addActionListener(this);
        btt_XoaNhap.addActionListener(this);
        dialogbtt_XoaNhap.addActionListener(this);
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_SuaNguyenLieu = new javax.swing.JDialog();
        dialog_Panel = new javax.swing.JPanel();
        lbl_MaMonAnDialog = new javax.swing.JLabel();
        lbl_MaNguyenLieu = new javax.swing.JLabel();
        lbl_TenNguyenLieu = new javax.swing.JLabel();
        lbl_SoLuong = new javax.swing.JLabel();
        dialogtxt_MaMonAn = new javax.swing.JTextField();
        dialogtxt_MaNguyenLieu = new javax.swing.JTextField();
        dialogtxt_TenNguyenLieu = new javax.swing.JTextField();
        dialogtxt_SoLuong = new javax.swing.JTextField();
        dialogbtt_Nhap = new javax.swing.JButton();
        dialogbtt_Xoa = new javax.swing.JButton();
        dialogbtt_Sua = new javax.swing.JButton();
        dialogbtt_XoaNhap = new javax.swing.JButton();
        dialog_ScrollPane = new javax.swing.JScrollPane();
        tbl_SuaNguyenLieu = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        lbl_MaMonAn = new javax.swing.JLabel();
        lbl_TenMonAn = new javax.swing.JLabel();
        lbl_DonGia = new javax.swing.JLabel();
        txt_MaMonAn = new javax.swing.JTextField();
        txt_TenMonAn = new javax.swing.JTextField();
        txt_DonGia = new javax.swing.JTextField();
        btt_Nhap = new javax.swing.JButton();
        btt_Xoa = new javax.swing.JButton();
        btt_Sua = new javax.swing.JButton();
        btt_XoaNhap = new javax.swing.JButton();
        ScrollPane = new javax.swing.JScrollPane();
        tbl_QLMonAn = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txt_Search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        QLSA_toolBar = new javax.swing.JMenu();
        QLMA_toolBar = new javax.swing.JMenu();
        QLNL_toolBar = new javax.swing.JMenu();
        QLNV_toolBar = new javax.swing.JMenu();

        dialog_SuaNguyenLieu.setTitle("Sửa Nguyên Liệu");

        dialog_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 2));

        lbl_MaMonAnDialog.setText("Mã Món Ăn");

        lbl_MaNguyenLieu.setText("Mã Nguyên Liệu");

        lbl_TenNguyenLieu.setText("Tên Nguyên Liệu");

        lbl_SoLuong.setText("Số Lượng");

        dialogbtt_Nhap.setText("Nhập");
        dialogbtt_Nhap.setPreferredSize(new java.awt.Dimension(83, 23));

        dialogbtt_Xoa.setText("Xóa");

        dialogbtt_Sua.setText("Sửa");
        dialogbtt_Sua.setPreferredSize(new java.awt.Dimension(83, 23));

        dialogbtt_XoaNhap.setText("Xóa Nhập");

        javax.swing.GroupLayout dialog_PanelLayout = new javax.swing.GroupLayout(dialog_Panel);
        dialog_Panel.setLayout(dialog_PanelLayout);
        dialog_PanelLayout.setHorizontalGroup(
            dialog_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialog_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_TenNguyenLieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialog_PanelLayout.createSequentialGroup()
                        .addGroup(dialog_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_MaMonAnDialog)
                            .addComponent(lbl_MaNguyenLieu)
                            .addComponent(lbl_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dialog_PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(dialog_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dialogbtt_XoaNhap)
                            .addComponent(dialogbtt_Nhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(dialog_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialog_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dialogtxt_SoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addComponent(dialogtxt_TenNguyenLieu)
                        .addComponent(dialogtxt_MaNguyenLieu)
                        .addComponent(dialogtxt_MaMonAn))
                    .addGroup(dialog_PanelLayout.createSequentialGroup()
                        .addGroup(dialog_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dialogbtt_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dialogbtt_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        dialog_PanelLayout.setVerticalGroup(
            dialog_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_PanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(dialog_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MaMonAnDialog)
                    .addComponent(dialogtxt_MaMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialog_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MaNguyenLieu)
                    .addComponent(dialogtxt_MaNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialog_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TenNguyenLieu)
                    .addComponent(dialogtxt_TenNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(dialog_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SoLuong)
                    .addComponent(dialogtxt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(dialog_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialogbtt_Nhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialogbtt_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialog_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialogbtt_XoaNhap)
                    .addComponent(dialogbtt_Xoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialog_ScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 2));

        tbl_SuaNguyenLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã Món Ăn", "Mã Nguyên Liệu", "Tên Nguyên Liệu", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_SuaNguyenLieu.setColumnSelectionAllowed(true);
        tbl_SuaNguyenLieu.getTableHeader().setReorderingAllowed(false);
        dialog_ScrollPane.setViewportView(tbl_SuaNguyenLieu);
        tbl_SuaNguyenLieu.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbl_SuaNguyenLieu.getColumnModel().getColumnCount() > 0) {
            tbl_SuaNguyenLieu.getColumnModel().getColumn(0).setResizable(false);
            tbl_SuaNguyenLieu.getColumnModel().getColumn(1).setResizable(false);
            tbl_SuaNguyenLieu.getColumnModel().getColumn(2).setResizable(false);
            tbl_SuaNguyenLieu.getColumnModel().getColumn(3).setResizable(false);
            tbl_SuaNguyenLieu.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout dialog_SuaNguyenLieuLayout = new javax.swing.GroupLayout(dialog_SuaNguyenLieu.getContentPane());
        dialog_SuaNguyenLieu.getContentPane().setLayout(dialog_SuaNguyenLieuLayout);
        dialog_SuaNguyenLieuLayout.setHorizontalGroup(
            dialog_SuaNguyenLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_SuaNguyenLieuLayout.createSequentialGroup()
                .addComponent(dialog_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dialog_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialog_SuaNguyenLieuLayout.setVerticalGroup(
            dialog_SuaNguyenLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dialog_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dialog_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sửa Nguyên Liệu Trong Món Ăn");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(204, 204, 0));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setText("Nhấn đúp chuột vào món ăn trên bảng để thực\nhiện chỉnh sửa nguyên liệu dùng cho món ăn");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_MaMonAn.setText("Mã Món Ăn");

        lbl_TenMonAn.setText("Tên Món Ăn");

        lbl_DonGia.setText("Đơn Giá");

        btt_Nhap.setText("Nhập");

        btt_Xoa.setText("Xóa");

        btt_Sua.setText("Sửa");

        btt_XoaNhap.setText("Xóa Nhập");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btt_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btt_Nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btt_Xoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btt_XoaNhap, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_TenMonAn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_DonGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_MaMonAn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_DonGia)
                            .addComponent(txt_TenMonAn)
                            .addComponent(txt_MaMonAn))))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MaMonAn)
                    .addComponent(txt_MaMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TenMonAn)
                    .addComponent(txt_TenMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_DonGia)
                    .addComponent(txt_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btt_Nhap)
                    .addComponent(btt_Xoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btt_Sua)
                    .addComponent(btt_XoaNhap))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        tbl_QLMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Món Ăn", "Tên Món Ăn", "Đơn Giá "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_QLMonAn.setColumnSelectionAllowed(true);
        tbl_QLMonAn.getTableHeader().setReorderingAllowed(false);
        tbl_QLMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_QLMonAnMouseClicked(evt);
            }
        });
        ScrollPane.setViewportView(tbl_QLMonAn);
        tbl_QLMonAn.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbl_QLMonAn.getColumnModel().getColumnCount() > 0) {
            tbl_QLMonAn.getColumnModel().getColumn(0).setResizable(false);
            tbl_QLMonAn.getColumnModel().getColumn(1).setResizable(false);
            tbl_QLMonAn.getColumnModel().getColumn(2).setResizable(false);
        }
        ListSelectionModel selectionModel = tbl_QLMonAn.getSelectionModel();

        selectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (!selectionModel.isSelectionEmpty()) {
                    btt_Sua.setEnabled(true);
                    btt_Xoa.setEnabled(true);
                    if(e.getValueIsAdjusting()){
                        txt_MaMonAn.setEnabled(false);
                        int selectedRow = tbl_QLMonAn.getSelectedRow();
                        if(selectedRow != -1){
                            //lấy dữ liệu
                            Object ma = tbl_QLMonAn.getValueAt(selectedRow, 0);
                            Object ten = tbl_QLMonAn.getValueAt(selectedRow, 1);
                            Object dongia = tbl_QLMonAn.getValueAt(selectedRow, 2);

                            //gán dữ liệu
                            txt_MaMonAn.setText(ma.toString());
                            txt_TenMonAn.setText(ten.toString());
                            txt_DonGia.setText(dongia.toString());
                        }
                    }
                }else {
                    btt_Sua.setEnabled(true);
                    btt_Xoa.setEnabled(true);
                    txt_MaMonAn.setEnabled(true);
                }
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txt_Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        txt_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_SearchKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Search)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Search)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        QLSA_toolBar.setText("Quản Lý Suất Ăn");
        QLSA_toolBar.setToolTipText("");
        QLSA_toolBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLSA_toolBarMouseClicked(evt);
            }
        });
        jMenuBar1.add(QLSA_toolBar);

        QLMA_toolBar.setText("Quản Lý Món Ăn");
        jMenuBar1.add(QLMA_toolBar);

        QLNL_toolBar.setText("Quản Lý Nguyên Liệu");
        QLNL_toolBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLNL_toolBarMouseClicked(evt);
            }
        });
        jMenuBar1.add(QLNL_toolBar);

        QLNV_toolBar.setText("Quản Lý Nhân Viên");
        QLNV_toolBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLNV_toolBarMouseClicked(evt);
            }
        });
        jMenuBar1.add(QLNV_toolBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Events
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btt_Nhap) {
            btt_NhapClick();
        } else if (e.getSource() == dialogbtt_Nhap) {
            dialogbtt_NhapClick();
        } else if (e.getSource() == btt_Sua) {
            btt_SuaClick();
        } else if (e.getSource() == dialogbtt_Sua) {
            dialogbtt_SuaClick();
        } else if (e.getSource() == btt_Xoa) {
            btt_XoaClick();
        } else if (e.getSource() == dialogbtt_Xoa) {
            dialogbtt_XoaClick();
        } else if (e.getSource() == btt_XoaNhap) {
            btt_XoaNhapClick();
        } else if (e.getSource() == dialogbtt_XoaNhap) {
            dialogbtt_XoaNhapClick();
        }
    }
    
    public void btt_NhapClick(){
        monAn = new MonAn();
    
        String maMonAnStr = txt_MaMonAn.getText();
        String tenMonAn = txt_TenMonAn.getText();
        String donGiaStr = txt_DonGia.getText();

        String errorMessage = validateInputValues(maMonAnStr, tenMonAn, donGiaStr);
        if (errorMessage != null) {
            JOptionPane.showMessageDialog(rootPane, errorMessage, "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double donGia = Double.parseDouble(donGiaStr);

        monAn.setmaMon(maMonAnStr);
        monAn.setTenMon(tenMonAn);
        monAn.setgia(donGia);

        if (new MonAnDAO().ThemMonAn(monAn)) { // Thêm món ăn thành công
            JOptionPane.showMessageDialog(rootPane, "Thêm món ăn thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            loadTableMA();
            btt_XoaNhapClick();
        } else { // Thêm món ăn không thành công
            JOptionPane.showMessageDialog(rootPane, "Thêm món ăn không thành công!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
        dialog_SuaNguyenLieu.setVisible(true);
    }
    
    public void btt_XoaClick(){
        String ma = txt_MaMonAn.getText();
        if(new MonAnDAO().xoaMonAn(ma)) {
            JOptionPane.showMessageDialog(rootPane, "Xóa Thành Công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            
            //Update
            DefaultTableModel model = (DefaultTableModel) tbl_QLMonAn.getModel();
            int selectedIndex = tbl_QLMonAn.getSelectedRow();
            if(selectedIndex >= 0){
                model.removeRow(selectedIndex);
                loadTableMA();
                btt_XoaNhapClick();
            }
        } else {
          JOptionPane.showMessageDialog(rootPane, "Xóa Không Thành Công", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }
    public void btt_XoaNhapClick(){
        txt_MaMonAn.setEnabled(true);
        txt_MaMonAn.setText("");
        txt_TenMonAn.setText("");
        txt_DonGia.setText("");
    }
    
    public void btt_SuaClick(){
        monAn = new MonAn();
        String maMonAnStr = txt_MaMonAn.getText();
        String tenMonAn = txt_TenMonAn.getText();
        String donGiaStr = txt_DonGia.getText();

        String errorMessage = validateInputValues(maMonAnStr, tenMonAn, donGiaStr);
        if (errorMessage != null) {
            JOptionPane.showMessageDialog(rootPane, errorMessage, "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double donGia = Double.parseDouble(donGiaStr);

        monAn.setmaMon(maMonAnStr);
        monAn.setTenMon(tenMonAn);
        monAn.setgia(donGia);

        if(new MonAnDAO().CapNhatMonAn(monAn)) { // Cập nhật món ăn thành công
            JOptionPane.showMessageDialog(rootPane, "Cập nhật món ăn thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            loadTableMA();
            btt_XoaNhapClick();
        } else { // Cập nhật món ăn không thành công
            JOptionPane.showMessageDialog(rootPane, "Cập nhật món ăn không thành công!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void dialogbtt_NhapClick(){
        
    }
    
    public void dialogbtt_XoaClick(){
        
    }
    
    public void dialogbtt_XoaNhapClick(){
        
    }
    
    public void dialogbtt_SuaClick(){
        
    }
    private void QLSA_toolBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLSA_toolBarMouseClicked
        new QLSuatAnView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_QLSA_toolBarMouseClicked

    private void QLNL_toolBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLNL_toolBarMouseClicked
        new QLNLView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_QLNL_toolBarMouseClicked

    private void QLNV_toolBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLNV_toolBarMouseClicked
        new QLNhanVienView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_QLNV_toolBarMouseClicked

    private void txt_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SearchKeyReleased
        String keyword = txt_Search.getText().toLowerCase(); // Lấy giá trị đã nhập và chuyển đổi sang chữ thường
        DefaultTableModel tableModel = (DefaultTableModel) tbl_QLMonAn.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tableModel); // Tạo đối tượng RowSorter để sắp xếp và lọc dữ liệu trên bảng
        tbl_QLMonAn.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + keyword));// Lọc các hàng trên bảng theo chuỗi tìm kiếm, không phân biệt hoa thường
    }//GEN-LAST:event_txt_SearchKeyReleased

    Set<Integer> selectedRows = new HashSet<>();
    Set<Integer> selectedCols = new HashSet<>();
    private void tbl_QLMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_QLMonAnMouseClicked
        int row = tbl_QLMonAn.rowAtPoint(evt.getPoint());
        int col = tbl_QLMonAn.columnAtPoint(evt.getPoint());
        if(evt.getClickCount() == 2){
            dialog_SuaNguyenLieu.setVisible(true);
            String ma = tbl_QLMonAn.getValueAt(row, 0).toString();
            loadTableNgLieu(ma);
        }else if (row >= 0 && col >= 0 && SwingUtilities.isLeftMouseButton(evt)) {
            // If cell is already selected and isSelected is true, then deselect it
            if (selectedRows.contains(row) && selectedCols.contains(col)) {
                tbl_QLMonAn.removeRowSelectionInterval(row, row);
                tbl_QLMonAn.removeColumnSelectionInterval(col, col);
                selectedRows.remove(row);
                selectedCols.remove(col);
                btt_XoaNhapClick();
            } else {
                // Otherwise, select the cell
                tbl_QLMonAn.addRowSelectionInterval(row, row);
                tbl_QLMonAn.addColumnSelectionInterval(col, col);
                selectedRows.add(row);
                selectedCols.add(col);
            }
        }
    }//GEN-LAST:event_tbl_QLMonAnMouseClicked
    
  
       
    private void load(){
        btt_Sua.setEnabled(false);
        btt_Xoa.setEnabled(false);
        loadTableMA();
    }
    public String validateInputValues(String maMonAn, String tenMonAn, String donGia) {
        if (maMonAn.isEmpty() || tenMonAn.isEmpty() || donGia.isEmpty()) {
            return "Vui lòng nhập đầy đủ thông tin!";
        }

        try {
            Double.parseDouble(donGia);
        } catch (NumberFormatException e) {
            return "Đơn giá phải là số thực!";
        }

        return null; // trả về null nếu không có lỗi nào xảy ra
    }

    private void loadTableMA(){
        list = new MonAnDAO().getListMA();
        DefaultTableModel model = (DefaultTableModel) tbl_QLMonAn.getModel();
        model.setRowCount(0);
        int n = list.size()-1;
        int count = 1;
        for(int i = 0 ; i <= n; i++){
            MonAn tmp = list.get(i);
            model.addRow(new Object[]{
                count, tmp.getMaMon(), tmp.getTenMon(), tmp.getdongia()
            });
        }
    }
    
    private void loadTableNgLieu(String ma){
        dialogbtt_Sua.setEnabled(false);
        dialogbtt_Xoa.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) tbl_SuaNguyenLieu.getModel();
        model = new MonAnDAO().GetModelNgLieu(model, ma);
        tbl_SuaNguyenLieu.setModel(model);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu QLMA_toolBar;
    private javax.swing.JMenu QLNL_toolBar;
    private javax.swing.JMenu QLNV_toolBar;
    private javax.swing.JMenu QLSA_toolBar;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton btt_Nhap;
    private javax.swing.JButton btt_Sua;
    private javax.swing.JButton btt_Xoa;
    private javax.swing.JButton btt_XoaNhap;
    private javax.swing.JPanel dialog_Panel;
    private javax.swing.JScrollPane dialog_ScrollPane;
    private javax.swing.JDialog dialog_SuaNguyenLieu;
    private javax.swing.JButton dialogbtt_Nhap;
    private javax.swing.JButton dialogbtt_Sua;
    private javax.swing.JButton dialogbtt_Xoa;
    private javax.swing.JButton dialogbtt_XoaNhap;
    private javax.swing.JTextField dialogtxt_MaMonAn;
    private javax.swing.JTextField dialogtxt_MaNguyenLieu;
    private javax.swing.JTextField dialogtxt_SoLuong;
    private javax.swing.JTextField dialogtxt_TenNguyenLieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_DonGia;
    private javax.swing.JLabel lbl_MaMonAn;
    private javax.swing.JLabel lbl_MaMonAnDialog;
    private javax.swing.JLabel lbl_MaNguyenLieu;
    private javax.swing.JLabel lbl_SoLuong;
    private javax.swing.JLabel lbl_TenMonAn;
    private javax.swing.JLabel lbl_TenNguyenLieu;
    private javax.swing.JTable tbl_QLMonAn;
    private javax.swing.JTable tbl_SuaNguyenLieu;
    private javax.swing.JTextField txt_DonGia;
    private javax.swing.JTextField txt_MaMonAn;
    private javax.swing.JTextField txt_Search;
    private javax.swing.JTextField txt_TenMonAn;
    // End of variables declaration//GEN-END:variables
    
    
}
