/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;
import Controller.NhanVienDAO;
import Model.ChamCong;
import Model.NhanVien;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author anhtu
 */
public class QLNhanVienViewPanel extends javax.swing.JPanel implements ActionListener{
    private NhanVien nv;
    private ArrayList<NhanVien> list = new NhanVienDAO().getListNV();
    /**
     * Creates new form QLNhanVienViewPanel
     */
    public QLNhanVienViewPanel() {
        initComponents();
        btt_ThemNhanVien.addActionListener(this);
        btt_XoaNhanVien.addActionListener(this);
        btt_XoaNhapNhanVien.addActionListener(this);
        btt_CapNhatNhanVien.addActionListener(this);
        dialogbtt_Sua.addActionListener(this);
        dialogbtt_Xoa.addActionListener(this);
        dialogbtt_XoaNhap.addActionListener(this);
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_ChamCong = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        dialoglbl_MaNhanVien = new javax.swing.JLabel();
        dialogtxt_MaNhanVien = new javax.swing.JTextField();
        dialogtxt_SoGioLam = new javax.swing.JTextField();
        dialoglbl_SoGioLam = new javax.swing.JLabel();
        dialogtxt_Luong = new javax.swing.JTextField();
        dialoglbl_Luong = new javax.swing.JLabel();
        dialoglbl_NgayCham = new javax.swing.JLabel();
        dialogtxt_NgayCham = new com.toedter.calendar.JDateChooser();
        dialogbtt_Sua = new javax.swing.JButton();
        dialogbtt_Xoa = new javax.swing.JButton();
        dialogbtt_XoaNhap = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_ChamCong = new javax.swing.JTable();
        dialogtxt_Search = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_MaNhanVien = new javax.swing.JLabel();
        txt_MaNhanVien = new javax.swing.JTextField();
        lbl_HoVaTen = new javax.swing.JLabel();
        txt_HoVaTen = new javax.swing.JTextField();
        lbl_GioiTinh = new javax.swing.JLabel();
        lbl_Tuoi = new javax.swing.JLabel();
        txt_Tuoi = new javax.swing.JTextField();
        lbl_SDT = new javax.swing.JLabel();
        txt_SoDienThoai = new javax.swing.JTextField();
        btt_ThemNhanVien = new javax.swing.JButton();
        btt_XoaNhapNhanVien = new javax.swing.JButton();
        btt_XoaNhanVien = new javax.swing.JButton();
        btt_CapNhatNhanVien = new javax.swing.JButton();
        txt_GioiTinh = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_NhanVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txt_Search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        dialog_ChamCong.setTitle("Thông Tin Chấm Công");

        dialoglbl_MaNhanVien.setText("Mã Nhân Viên");

        dialoglbl_SoGioLam.setText("Số Giờ Làm");

        dialoglbl_Luong.setText("Lương Theo Giờ");

        dialoglbl_NgayCham.setText("Ngày Chấm");

        dialogbtt_Sua.setText("Sửa");

        dialogbtt_Xoa.setText("Xóa");

        dialogbtt_XoaNhap.setText("Xóa Nhập");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dialoglbl_MaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dialoglbl_SoGioLam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dialoglbl_NgayCham, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dialoglbl_Luong))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dialogtxt_MaNhanVien)
                            .addComponent(dialogtxt_SoGioLam)
                            .addComponent(dialogtxt_Luong)
                            .addComponent(dialogtxt_NgayCham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(dialogbtt_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(dialogbtt_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 74, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(dialogbtt_XoaNhap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialoglbl_MaNhanVien)
                    .addComponent(dialogtxt_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialoglbl_SoGioLam)
                    .addComponent(dialogtxt_SoGioLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialoglbl_Luong)
                    .addComponent(dialogtxt_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dialoglbl_NgayCham)
                    .addComponent(dialogtxt_NgayCham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dialogbtt_Sua)
                    .addComponent(dialogbtt_Xoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dialogbtt_XoaNhap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_ChamCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Nhân Viên", "Số Giờ Làm", "Lương Theo Giờ", "Ngày chấm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_ChamCong.setColumnSelectionAllowed(true);
        tbl_ChamCong.getTableHeader().setReorderingAllowed(false);
        tbl_ChamCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ChamCongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_ChamCong);
        ListSelectionModel selectionModel2 = tbl_ChamCong.getSelectionModel();

        selectionModel2.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (!selectionModel2.isSelectionEmpty()) {
                    dialogbtt_Sua.setEnabled(true);
                    dialogbtt_Xoa.setEnabled(true);
                    if(e.getValueIsAdjusting()){
                        dialogtxt_MaNhanVien.setEnabled(false);
                        int selectedRow = tbl_ChamCong.getSelectedRow();
                        if(selectedRow != -1){
                            //lay du lieu
                            Object ma = tbl_ChamCong.getValueAt(selectedRow, 1);
                            Object gioLam = tbl_ChamCong.getValueAt(selectedRow, 2);
                            Object luongTheoGio = tbl_ChamCong.getValueAt(selectedRow, 3);
                            Object NgayCham = tbl_ChamCong.getValueAt(selectedRow, 4);
                            //Gan du lieu
                            dialogtxt_MaNhanVien.setText(ma.toString());
                            dialogtxt_SoGioLam.setText(gioLam.toString());
                            dialogtxt_Luong.setText(luongTheoGio.toString());
                            dialogtxt_NgayCham.setDate((Date)NgayCham);          }
                    }
                }else {
                    dialogbtt_Sua.setEnabled(false);
                    dialogbtt_Xoa.setEnabled(false);
                    dialogtxt_MaNhanVien.setEnabled(true);
                }
            }
        });

        dialogtxt_Search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        dialogtxt_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dialogtxt_SearchKeyReleased(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/search.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setEnabled(false);

        javax.swing.GroupLayout dialog_ChamCongLayout = new javax.swing.GroupLayout(dialog_ChamCong.getContentPane());
        dialog_ChamCong.getContentPane().setLayout(dialog_ChamCongLayout);
        dialog_ChamCongLayout.setHorizontalGroup(
            dialog_ChamCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_ChamCongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialog_ChamCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addGroup(dialog_ChamCongLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dialogtxt_Search))))
        );
        dialog_ChamCongLayout.setVerticalGroup(
            dialog_ChamCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_ChamCongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialog_ChamCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dialogtxt_Search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
        );

        dialog_ChamCong.pack();
        dialog_ChamCong.setLocationRelativeTo(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_MaNhanVien.setText("Mã Nhân Viên");

        lbl_HoVaTen.setText("Họ và Tên");

        lbl_GioiTinh.setText("Giới Tính");

        lbl_Tuoi.setText("Tuổi");

        lbl_SDT.setText("Số Điện Thoại");

        btt_ThemNhanVien.setText("Thêm");

        btt_XoaNhapNhanVien.setText("Xóa Nhập");

        btt_XoaNhanVien.setText("Xóa");

        btt_CapNhatNhanVien.setText("Cập Nhật");

        txt_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_MaNhanVien))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_HoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_HoVaTen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_GioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_Tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Tuoi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_SoDienThoai))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btt_ThemNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btt_XoaNhapNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btt_CapNhatNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btt_XoaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MaNhanVien)
                    .addComponent(txt_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_HoVaTen)
                    .addComponent(txt_HoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_GioiTinh)
                    .addComponent(txt_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Tuoi)
                    .addComponent(txt_Tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SDT)
                    .addComponent(txt_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btt_ThemNhanVien)
                    .addComponent(btt_CapNhatNhanVien))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btt_XoaNhapNhanVien)
                    .addComponent(btt_XoaNhanVien))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        tbl_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Họ và Tên", "Giới Tính", "Tuổi", "Số Điện Thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_NhanVien.setColumnSelectionAllowed(true);
        tbl_NhanVien.getTableHeader().setReorderingAllowed(false);
        tbl_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NhanVienMouseClicked(evt);
            }
        });
        ListSelectionModel selectionModel = tbl_NhanVien.getSelectionModel();

        selectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (!selectionModel.isSelectionEmpty()) {
                    btt_CapNhatNhanVien.setEnabled(true);
                    btt_XoaNhanVien.setEnabled(true);
                    if(e.getValueIsAdjusting()){
                        txt_MaNhanVien.setEnabled(false);
                        int selectedRow = tbl_NhanVien.getSelectedRow();
                        if(selectedRow != -1){
                            //lay du lieu
                            Object ma = tbl_NhanVien.getValueAt(selectedRow, 0);
                            Object ten = tbl_NhanVien.getValueAt(selectedRow, 1);
                            Object gioitinh = tbl_NhanVien.getValueAt(selectedRow, 2);
                            Object tuoi = tbl_NhanVien.getValueAt(selectedRow, 3);
                            Object sodt = tbl_NhanVien.getValueAt(selectedRow, 4);
                            //Gan du lieu
                            txt_MaNhanVien.setText(ma.toString());
                            txt_HoVaTen.setText(ten.toString());
                            txt_GioiTinh.setSelectedItem(gioitinh);
                            txt_Tuoi.setText(tuoi.toString());
                            txt_SoDienThoai.setText(sodt.toString());            }
                    }
                }else {
                    btt_CapNhatNhanVien.setEnabled(false);
                    btt_XoaNhanVien.setEnabled(false);
                    txt_MaNhanVien.setEnabled(true);
                }
            }
        });
        jScrollPane1.setViewportView(tbl_NhanVien);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txt_Search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_SearchKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/search.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Search))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Search)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btt_ThemNhanVien)){
            bttThemNhanVienClicked();
        }else if(e.getSource().equals(btt_XoaNhanVien)){
            bttXoaNhanVienClicked();
        }else if(e.getSource().equals(btt_XoaNhapNhanVien)){
            bttXoaNhapNVClicked();
        }else if(e.getSource().equals(btt_CapNhatNhanVien)){
            bttCapNhatClicked();
        }else if(e.getSource().equals(dialogbtt_Sua)){
            dialogbtt_SuaClicked();
        }else if(e.getSource().equals(dialogbtt_Xoa)){
            dialogbtt_XoaClicked();
        }else if(e.getSource().equals(dialogbtt_XoaNhap)){
            dialogbtt_XoaNhapClicked();
        }
    }
    
    public void bttThemNhanVienClicked(){
        nv = new NhanVien();
        
        String maNVstr = txt_MaNhanVien.getText();
        String tenNV = txt_HoVaTen.getText();
        String gioiTinh = (String) txt_GioiTinh.getSelectedItem();
        String tuoi = txt_Tuoi.getText();
        String soDienThoai = txt_SoDienThoai.getText();
        
        String errorMessage = validateInputValues(maNVstr, tenNV, gioiTinh, tuoi, soDienThoai);
        if (errorMessage != null) {
            JOptionPane.showMessageDialog(this, errorMessage, "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
}       
        //
        int tuoiNV = Integer.parseInt(tuoi);
        boolean gt;
        if(gioiTinh == "Nam") gt = true;
        else gt = false;
        
        nv.setMaNV(maNVstr);
        nv.setTenNV(tenNV);
        nv.setGioiTinh(gt);
        nv.setTuoi(tuoiNV);
        nv.setsodienThoai(soDienThoai);
        
        if(new NhanVienDAO().ThemNhanVien(nv)) { // Thêm nhân viên thành công
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            loadTableNV();
            bttXoaNhapNVClicked();
        } else { // Thêm nhân viên không thành công
            JOptionPane.showMessageDialog(this, "Thêm nhân viên không thành công!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private String validateInputValues(String maNVstr, String tenNV, String gioiTinh, String tuoi, String soDienThoai) {
        if (maNVstr.isEmpty()) {
            return "Mã Nhân Viên không được để trống";
        }

        if (tenNV.isEmpty()) {
            return "Tên nhân viên không được để trống";
        }

        if (gioiTinh.isEmpty()) {
            return "Giới tính không được để trống";
        }
        
        if (tuoi.isEmpty()) {
            return "Tuổi không được để trống";
        }
        
        if(!isNumeric(tuoi)){
            return "Tuổi phải là số";
        }
        
        int age = Integer.parseInt(tuoi);
        
        if (age <= 0) {
            return "Tuổi phải lớn hơn 0";
        }

        if (soDienThoai.isEmpty()) {
            return "Số điện thoại không được để trống";
        }

        return null;
    }

    private boolean isNumeric(String str) {
      return str.matches("-?\\d+(\\.\\d+)?");
    }
    
    public void bttXoaNhanVienClicked(){
        String maNV = txt_MaNhanVien.getText();
        if(new NhanVienDAO().xoaNhanVien(maNV)) {
            JOptionPane.showMessageDialog(this, "Xóa Thành Công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            
            //Update
            DefaultTableModel model = (DefaultTableModel) tbl_NhanVien.getModel();
            int selectedIndex = tbl_NhanVien.getSelectedRow();
            if(selectedIndex >= 0){
                model.removeRow(selectedIndex);
                loadTableNV();
                bttXoaNhapNVClicked();
            }
        } else {
          JOptionPane.showMessageDialog(this, "Xóa Không Thành Công", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void bttXoaNhapNVClicked(){
        txt_MaNhanVien.setEnabled(true);
        txt_MaNhanVien.setText("");
        txt_HoVaTen.setText("");
        txt_GioiTinh.setSelectedItem("Nam");
        txt_Tuoi.setText("");
        txt_SoDienThoai.setText("");
    }
    
    public void bttCapNhatClicked(){
        nv = new NhanVien();
        String maNVstr = txt_MaNhanVien.getText();
        String tenNV = txt_HoVaTen.getText();
        String gioiTinh = (String) txt_GioiTinh.getSelectedItem();
        String tuoi = txt_Tuoi.getText();
        String soDienThoai = txt_SoDienThoai.getText();

        String errorMessage = validateInputValues(maNVstr, tenNV, gioiTinh, tuoi, soDienThoai);
        if (errorMessage != null) {
            JOptionPane.showMessageDialog(this, errorMessage, "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int tuoiNV = Integer.parseInt(tuoi);
        boolean gt = gioiTinh.equals("Nam");

        nv.setMaNV(maNVstr);
        nv.setTenNV(tenNV);
        nv.setGioiTinh(gt);
        nv.setTuoi(tuoiNV);
        nv.setsodienThoai(soDienThoai);

        if(new NhanVienDAO().CapNhatNhanVien(nv)) { // Cập nhật nhân viên thành công
            JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            loadTableNV();
            bttXoaNhapNVClicked();
        } else { // Cập nhật nhân viên không thành công
            JOptionPane.showMessageDialog(this, "Cập nhật nhân viên không thành công!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    
    private void load(){
        btt_CapNhatNhanVien.setEnabled(false);
        btt_XoaNhanVien.setEnabled(false);
        loadTableNV();
    }
    
    private void loadTableNV(){
        list = new NhanVienDAO().getListNV();
        DefaultTableModel model = (DefaultTableModel) tbl_NhanVien.getModel();
        model.setRowCount(0);
        int n = list.size()-1;
        for(int i = 0 ; i <= n; i++){
            NhanVien tmp = list.get(i);
            boolean gt = tmp.getGioiTinh();
            String gioiTinh;
            if(gt == true) gioiTinh = "Nam";
            else gioiTinh = "Nữ";
            model.addRow(new Object[]{
                tmp.getMaNV(), tmp.getTenNV(), gioiTinh, tmp.getTuoi(), tmp.getsodienThoai()
            });
        }
        
    }
    
    private void loadTableChamCong(String ma){
        dialogbtt_Sua.setEnabled(false);
        dialogbtt_Xoa.setEnabled(false);
        ArrayList<ChamCong> list = new NhanVienDAO().getListChamCong(ma);
        DefaultTableModel model = (DefaultTableModel) tbl_ChamCong.getModel();
        model.setRowCount(0);
        int n = list.size()-1;
        int count = 1;
        for(int i = 0 ; i <= n; i++){
            ChamCong tmp = list.get(i);
            model.addRow(new Object[]{
                count, tmp.getmaNV(), tmp.getgioLam(), tmp.getLuongTheoGio(), tmp.getngayLam()
            });
            count++;
        }
    }
    
    private int selectedRow = -1;
    private int selectedCol = -1;
    private void tbl_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NhanVienMouseClicked
        int row = tbl_NhanVien.rowAtPoint(evt.getPoint());
        int col = tbl_NhanVien.columnAtPoint(evt.getPoint());

        // Check if the cell is valid and left mouse button is clicked
        if(evt.getClickCount() == 2){
            dialog_ChamCong.setVisible(true);
            String ma = tbl_NhanVien.getValueAt(row, 0).toString();
            loadTableChamCong(ma);
        }else if (row >= 0 && col >= 0 && SwingUtilities.isLeftMouseButton(evt)) {
            // If cell is already selected and isSelected is true, then deselect it
            if (row == selectedRow && col == selectedCol) {
                tbl_NhanVien.removeRowSelectionInterval(row, row);
                tbl_NhanVien.removeColumnSelectionInterval(0, 4);
                selectedRow = -1;
                selectedCol = -1;
                bttXoaNhapNVClicked();
            } else {
                // Otherwise, select the cell
                tbl_NhanVien.changeSelection(row, col, false, false);
                selectedRow = row;
                selectedCol = col;
            }
        }
    }//GEN-LAST:event_tbl_NhanVienMouseClicked

    private void txt_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SearchKeyReleased
        String keyword = txt_Search.getText().toLowerCase(); // Lấy giá trị đã nhập và chuyển đổi sang chữ thường
        DefaultTableModel tableModel = (DefaultTableModel) tbl_NhanVien.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tableModel); // Tạo đối tượng RowSorter để sắp xếp và lọc dữ liệu trên bảng
        tbl_NhanVien.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + keyword));// Lọc các hàng trên bảng theo chuỗi tìm kiếm, không phân biệt hoa thường
    }//GEN-LAST:event_txt_SearchKeyReleased
    
    private int selectedRow2 = -1;
    private int selectedCol2 = -1;
    private void tbl_ChamCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ChamCongMouseClicked
        int row = tbl_ChamCong.rowAtPoint(evt.getPoint());
        int col = tbl_ChamCong.columnAtPoint(evt.getPoint());

        if (row >= 0 && col >= 0 && SwingUtilities.isLeftMouseButton(evt)) {
            // If cell is already selected and isSelected is true, then deselect it
            if (row == selectedRow2 && col == selectedCol2) {
                tbl_ChamCong.removeRowSelectionInterval(row, row);
                tbl_ChamCong.removeColumnSelectionInterval(0, 4);
                selectedRow2 = -1;
                selectedCol2 = -1;
                bttXoaNhapNVClicked();
            } else {
                // Otherwise, select the cell
                tbl_ChamCong.changeSelection(row,col, false , false);
                selectedRow2 = row;
                selectedCol2 = col;
            }
        }
    }//GEN-LAST:event_tbl_ChamCongMouseClicked

    private void dialogtxt_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dialogtxt_SearchKeyReleased
        String keyword = dialogtxt_Search.getText().toLowerCase(); // Lấy giá trị đã nhập và chuyển đổi sang chữ thường
        DefaultTableModel tableModel = (DefaultTableModel) tbl_ChamCong.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tableModel); // Tạo đối tượng RowSorter để sắp xếp và lọc dữ liệu trên bảng
        tbl_ChamCong.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + keyword));// Lọc các hàng trên bảng theo chuỗi tìm kiếm, không phân biệt hoa thường
    }//GEN-LAST:event_dialogtxt_SearchKeyReleased

    private String validateInputValues(String maNVStr, String soGioLamStr, String luongTheoGioStr, java.sql.Date ngayCham) {
        if (maNVStr.isEmpty() || soGioLamStr.isEmpty() || luongTheoGioStr.isEmpty() || ngayCham == null) {
            return "Vui lòng điền đầy đủ thông tin";
        }

        try {
            Integer.parseInt(maNVStr);
        } catch (NumberFormatException e) {
            return "Mã nhân viên phải là một số nguyên";
        }

        try {
            Integer.parseInt(soGioLamStr);
        } catch (NumberFormatException e) {
            return "Số giờ làm phải là một số nguyên";
        }

        try {
            Double.parseDouble(luongTheoGioStr);
        } catch (NumberFormatException e) {
            return "Lương theo giờ phải là một số";
        }

        return null; // Trả về null nếu không có lỗi
    }
    
    private void dialogbtt_SuaClicked() {
        ChamCong cc = new ChamCong();
        String maNVStr = dialogtxt_MaNhanVien.getText();
        String soGioLamStr = dialogtxt_SoGioLam.getText();
        String luongTheoGioStr = dialogtxt_Luong.getText();
        Date selectedDate = dialogtxt_NgayCham.getDate();

        java.sql.Date ngayCham = null; 
        if (selectedDate != null) {
            // Chuyển đổi Date thành java.sql.Date
            ngayCham = new java.sql.Date(selectedDate.getTime());
        }

        // Validate input values
        String errorMessage = validateInputValues(maNVStr, soGioLamStr, luongTheoGioStr, ngayCham);
        if (errorMessage != null) {
          JOptionPane.showMessageDialog(this, errorMessage, "Lỗi", JOptionPane.ERROR_MESSAGE);
          return;
        }

        int maNV = Integer.parseInt(maNVStr);
        int soGioLam = Integer.parseInt(soGioLamStr);
        double luongTheoGio = Double.parseDouble(luongTheoGioStr);

        cc.setmaNV(maNVStr);
        cc.setgioLam(soGioLam);
        cc.setLuongTheoGio(luongTheoGio);
        cc.setngayLam(ngayCham);

        if(new NhanVienDAO().capNhatChamCong(cc)) {
          JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
          loadTableChamCong(maNVStr);
          dialogbtt_XoaNhapClicked();
        } else {
          JOptionPane.showMessageDialog(this, "Cập Nhật Không Thành Công", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void dialogbtt_XoaClicked() {
        String maNV = dialogtxt_MaNhanVien.getText();
        Date selectedDate = dialogtxt_NgayCham.getDate();
        java.sql.Date ngayCham = null; 
        if (selectedDate != null) {
            // Chuyển đổi Date thành java.sql.Date
            ngayCham = new java.sql.Date(selectedDate.getTime());
        }
        if(new NhanVienDAO().xoaChamCong(maNV,ngayCham)) {
            JOptionPane.showMessageDialog(this, "Xóa Thành Công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            
            //Update
            DefaultTableModel model = (DefaultTableModel) tbl_ChamCong.getModel();
            int selectedIndex = tbl_ChamCong.getSelectedRow();
            if(selectedIndex >= 0){
                model.removeRow(selectedIndex);
                loadTableChamCong(maNV);
                dialogbtt_XoaNhapClicked();
            }
        } else {
          JOptionPane.showMessageDialog(this, "Xóa Không Thành Công", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void dialogbtt_XoaNhapClicked(){
        dialogtxt_MaNhanVien.setEnabled(true);
        dialogtxt_NgayCham.setEnabled(true);
        dialogtxt_MaNhanVien.setText("");
        dialogtxt_SoGioLam.setText("");
        dialogtxt_Luong.setText("");
        dialogtxt_NgayCham.setDate(null);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_CapNhatNhanVien;
    private javax.swing.JButton btt_ThemNhanVien;
    private javax.swing.JButton btt_XoaNhanVien;
    private javax.swing.JButton btt_XoaNhapNhanVien;
    private javax.swing.JDialog dialog_ChamCong;
    private javax.swing.JButton dialogbtt_Sua;
    private javax.swing.JButton dialogbtt_Xoa;
    private javax.swing.JButton dialogbtt_XoaNhap;
    private javax.swing.JLabel dialoglbl_Luong;
    private javax.swing.JLabel dialoglbl_MaNhanVien;
    private javax.swing.JLabel dialoglbl_NgayCham;
    private javax.swing.JLabel dialoglbl_SoGioLam;
    private javax.swing.JTextField dialogtxt_Luong;
    private javax.swing.JTextField dialogtxt_MaNhanVien;
    private com.toedter.calendar.JDateChooser dialogtxt_NgayCham;
    private javax.swing.JTextField dialogtxt_Search;
    private javax.swing.JTextField dialogtxt_SoGioLam;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_GioiTinh;
    private javax.swing.JLabel lbl_HoVaTen;
    private javax.swing.JLabel lbl_MaNhanVien;
    private javax.swing.JLabel lbl_SDT;
    private javax.swing.JLabel lbl_Tuoi;
    private javax.swing.JTable tbl_ChamCong;
    private javax.swing.JTable tbl_NhanVien;
    private javax.swing.JComboBox<String> txt_GioiTinh;
    private javax.swing.JTextField txt_HoVaTen;
    private javax.swing.JTextField txt_MaNhanVien;
    private javax.swing.JTextField txt_Search;
    private javax.swing.JTextField txt_SoDienThoai;
    private javax.swing.JTextField txt_Tuoi;
    // End of variables declaration//GEN-END:variables
}
