/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.NhanVienDAO;
import Model.NhanVien;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author anhtu
 */
public class QLNhanVienView extends javax.swing.JFrame implements ActionListener{
    private NhanVien nv;
    private ArrayList<NhanVien> list = new NhanVienDAO().getListNV();
    /**
     * Creates new form QLNhanVienView
     */
    public QLNhanVienView() {
        initComponents();
        btt_ThemNhanVien.addActionListener(this);
        btt_XoaNhanVien.addActionListener(this);
        btt_XoaNhapNhanVien.addActionListener(this);
        btt_CapNhatNhanVien.addActionListener(this);
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_ChamCong = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        dialoglbl_MaNhanVien = new javax.swing.JLabel();
        dialogtxt_MaNhanVien = new javax.swing.JTextField();
        dialogtxt_SoGioLam = new javax.swing.JTextField();
        dialoglbl_SoGioLam = new javax.swing.JLabel();
        dialogtxt_Luong = new javax.swing.JTextField();
        dialoglbl_Luong = new javax.swing.JLabel();
        dialoglbl_NgayCham = new javax.swing.JLabel();
        dialogtxt_NgayCham = new com.toedter.calendar.JDateChooser();
        dialogbtt_Sua = new javax.swing.JButton();
        dialogbtt_TimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_ChamCong = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbl_MaNhanVien = new javax.swing.JLabel();
        txt_MaNhanVien = new javax.swing.JTextField();
        lbl_HoVaTen = new javax.swing.JLabel();
        txt_HoVaTen = new javax.swing.JTextField();
        lbl_GioiTinh = new javax.swing.JLabel();
        lbl_Tuoi = new javax.swing.JLabel();
        txt_Tuoi = new javax.swing.JTextField();
        lbl_SDT = new javax.swing.JLabel();
        txt_SoDienThoai = new javax.swing.JTextField();
        btt_ThemNhanVien = new javax.swing.JButton();
        btt_XoaNhapNhanVien = new javax.swing.JButton();
        btt_XoaNhanVien = new javax.swing.JButton();
        btt_CapNhatNhanVien = new javax.swing.JButton();
        txt_GioiTinh = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_NhanVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txt_Search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btt_QLSuatAn = new javax.swing.JMenu();
        btt_QLMonAn = new javax.swing.JMenu();
        btt_QLNguyenLieu = new javax.swing.JMenu();
        btt_QLNhanVien = new javax.swing.JMenu();

        dialoglbl_MaNhanVien.setText("Mã Nhân Viên");

        dialoglbl_SoGioLam.setText("Số Giờ Làm");

        dialoglbl_Luong.setText("Lương Theo Giờ");

        dialoglbl_NgayCham.setText("Ngày Chấm");

        dialogbtt_Sua.setText("Sửa");

        dialogbtt_TimKiem.setText("Tìm Kiếm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dialoglbl_NgayCham, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 37, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dialoglbl_MaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 25, Short.MAX_VALUE)
                                .addComponent(dialogbtt_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dialoglbl_SoGioLam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dialoglbl_Luong)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dialogtxt_MaNhanVien)
                    .addComponent(dialogtxt_SoGioLam)
                    .addComponent(dialogtxt_Luong)
                    .addComponent(dialogtxt_NgayCham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(dialogbtt_TimKiem)
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialoglbl_MaNhanVien)
                    .addComponent(dialogtxt_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialoglbl_SoGioLam)
                    .addComponent(dialogtxt_SoGioLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialoglbl_Luong)
                    .addComponent(dialogtxt_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dialoglbl_NgayCham)
                    .addComponent(dialogtxt_NgayCham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dialogbtt_TimKiem)
                    .addComponent(dialogbtt_Sua))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tbl_ChamCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Số Giờ Làm", "Lương Theo Giờ", "Ngày chấm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_ChamCong.setColumnSelectionAllowed(true);
        tbl_ChamCong.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbl_ChamCong);
        tbl_ChamCong.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbl_ChamCong.getColumnModel().getColumnCount() > 0) {
            tbl_ChamCong.getColumnModel().getColumn(0).setResizable(false);
            tbl_ChamCong.getColumnModel().getColumn(1).setResizable(false);
            tbl_ChamCong.getColumnModel().getColumn(2).setResizable(false);
            tbl_ChamCong.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout dialog_ChamCongLayout = new javax.swing.GroupLayout(dialog_ChamCong.getContentPane());
        dialog_ChamCong.getContentPane().setLayout(dialog_ChamCongLayout);
        dialog_ChamCongLayout.setHorizontalGroup(
            dialog_ChamCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_ChamCongLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dialog_ChamCongLayout.setVerticalGroup(
            dialog_ChamCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_MaNhanVien.setText("Mã Nhân Viên");

        lbl_HoVaTen.setText("Họ và Tên");

        lbl_GioiTinh.setText("Giới Tính");

        lbl_Tuoi.setText("Tuổi");

        lbl_SDT.setText("Số Điện Thoại");

        btt_ThemNhanVien.setText("Thêm");

        btt_XoaNhapNhanVien.setText("Xóa Nhập");

        btt_XoaNhanVien.setText("Xóa");

        btt_CapNhatNhanVien.setText("Cập Nhật");

        txt_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_MaNhanVien))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_HoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_HoVaTen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_GioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_Tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Tuoi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_SoDienThoai))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btt_ThemNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btt_XoaNhapNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btt_CapNhatNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btt_XoaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MaNhanVien)
                    .addComponent(txt_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_HoVaTen)
                    .addComponent(txt_HoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_GioiTinh)
                    .addComponent(txt_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Tuoi)
                    .addComponent(txt_Tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SDT)
                    .addComponent(txt_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btt_ThemNhanVien)
                    .addComponent(btt_CapNhatNhanVien))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btt_XoaNhapNhanVien)
                    .addComponent(btt_XoaNhanVien))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        tbl_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Họ và Tên", "Giới Tính", "Tuổi", "Số Điện Thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_NhanVien.setColumnSelectionAllowed(true);
        tbl_NhanVien.getTableHeader().setReorderingAllowed(false);
        tbl_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NhanVienMouseClicked(evt);
            }
        });
        ListSelectionModel selectionModel = tbl_NhanVien.getSelectionModel();

        selectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (!selectionModel.isSelectionEmpty()) {
                    btt_CapNhatNhanVien.setEnabled(true);
                    btt_XoaNhanVien.setEnabled(true);
                    if(e.getValueIsAdjusting()){
                        txt_MaNhanVien.setEnabled(false);
                        int selectedRow = tbl_NhanVien.getSelectedRow();
                        if(selectedRow != -1){
                            //lay du lieu
                            Object ma = tbl_NhanVien.getValueAt(selectedRow, 0);
                            Object ten = tbl_NhanVien.getValueAt(selectedRow, 1);
                            Object gioitinh = tbl_NhanVien.getValueAt(selectedRow, 2);
                            Object tuoi = tbl_NhanVien.getValueAt(selectedRow, 3);
                            Object sodt = tbl_NhanVien.getValueAt(selectedRow, 4);
                            //Gan du lieu
                            txt_MaNhanVien.setText(ma.toString());
                            txt_HoVaTen.setText(ten.toString());
                            txt_GioiTinh.setSelectedItem(gioitinh);
                            txt_Tuoi.setText(tuoi.toString());
                            txt_SoDienThoai.setText(sodt.toString());            }
                    }
                }else {
                    btt_CapNhatNhanVien.setEnabled(false);
                    btt_XoaNhanVien.setEnabled(false);
                    txt_MaNhanVien.setEnabled(true);
                }
            }
        });
        jScrollPane1.setViewportView(tbl_NhanVien);
        tbl_NhanVien.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbl_NhanVien.getColumnModel().getColumnCount() > 0) {
            tbl_NhanVien.getColumnModel().getColumn(0).setResizable(false);
            tbl_NhanVien.getColumnModel().getColumn(1).setResizable(false);
            tbl_NhanVien.getColumnModel().getColumn(2).setResizable(false);
            tbl_NhanVien.getColumnModel().getColumn(3).setResizable(false);
            tbl_NhanVien.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txt_Search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_SearchKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Search))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Search)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        btt_QLSuatAn.setText("Quản Lý Suất Ăn");
        btt_QLSuatAn.setToolTipText("");
        btt_QLSuatAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btt_QLSuatAnMouseClicked(evt);
            }
        });
        jMenuBar1.add(btt_QLSuatAn);

        btt_QLMonAn.setText("Quản Lý Món Ăn");
        btt_QLMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btt_QLMonAnMouseClicked(evt);
            }
        });
        jMenuBar1.add(btt_QLMonAn);

        btt_QLNguyenLieu.setText("Quản Lý Nguyên Liệu");
        btt_QLNguyenLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btt_QLNguyenLieuMouseClicked(evt);
            }
        });
        jMenuBar1.add(btt_QLNguyenLieu);

        btt_QLNhanVien.setText("Quản Lý Nhân Viên");
        jMenuBar1.add(btt_QLNhanVien);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Events
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btt_ThemNhanVien)){
            bttThemNhanVienClicked();
        }else if(e.getSource().equals(btt_XoaNhanVien)){
            bttXoaNhanVienClicked();
        }else if(e.getSource().equals(btt_XoaNhapNhanVien)){
            bttXoaNhapNVClicked();
        }else if(e.getSource().equals(btt_CapNhatNhanVien)){
            bttCapNhatClicked();
        }
    }
    
    public void bttThemNhanVienClicked(){
        nv = new NhanVien();
        
        String maNVstr = txt_MaNhanVien.getText();
        String tenNV = txt_HoVaTen.getText();
        String gioiTinh = (String) txt_GioiTinh.getSelectedItem();
        String tuoi = txt_Tuoi.getText();
        String soDienThoai = txt_SoDienThoai.getText();
        
        String errorMessage = validateInputValues(maNVstr, tenNV, gioiTinh, tuoi, soDienThoai);
        if (errorMessage != null) {
            JOptionPane.showMessageDialog(rootPane, errorMessage, "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
}       
        //
        int tuoiNV = Integer.parseInt(tuoi);
        boolean gt;
        if(gioiTinh == "Nam") gt = true;
        else gt = false;
        
        nv.setMaNV(maNVstr);
        nv.setTenNV(tenNV);
        nv.setGioiTinh(gt);
        nv.setTuoi(tuoiNV);
        nv.setsodienThoai(soDienThoai);
        
        if(new NhanVienDAO().ThemNhanVien(nv)) { // Thêm nhân viên thành công
            JOptionPane.showMessageDialog(rootPane, "Thêm nhân viên thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            loadTable();            
        } else { // Thêm nhân viên không thành công
            JOptionPane.showMessageDialog(rootPane, "Thêm nhân viên không thành công!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private String validateInputValues(String maNVstr, String tenNV, String gioiTinh, String tuoi, String soDienThoai) {
        if (maNVstr.isEmpty()) {
            return "Mã Nhân Viên không được để trống";
        }

        if (tenNV.isEmpty()) {
            return "Tên nhân viên không được để trống";
        }

        if (gioiTinh.isEmpty()) {
            return "Giới tính không được để trống";
        }
        
        if (tuoi.isEmpty()) {
            return "Tuổi không được để trống";
        }
        
        if(!isNumeric(tuoi)){
            return "Tuổi phải là số";
        }
        
        int age = Integer.parseInt(tuoi);
        
        if (age <= 0) {
            return "Tuổi phải lớn hơn 0";
        }

        if (soDienThoai.isEmpty()) {
            return "Số điện thoại không được để trống";
        }

        return null;
    }

    private boolean isNumeric(String str) {
      return str.matches("-?\\d+(\\.\\d+)?");
    }
    
    public void bttXoaNhanVienClicked(){
        String maNV = txt_MaNhanVien.getText();
        if(new NhanVienDAO().xoaNhanVien(maNV)) {
            JOptionPane.showMessageDialog(rootPane, "Xóa Thành Công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            
            //Update
            DefaultTableModel model = (DefaultTableModel) tbl_NhanVien.getModel();
            int selectedIndex = tbl_NhanVien.getSelectedRow();
            if(selectedIndex >= 0){
                model.removeRow(selectedIndex);
                loadTable();
                bttXoaNhapNVClicked();
            }
        } else {
          JOptionPane.showMessageDialog(rootPane, "Xóa Không Thành Công", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void bttXoaNhapNVClicked(){
        txt_MaNhanVien.setEnabled(true);
        txt_MaNhanVien.setText("");
        txt_HoVaTen.setText("");
        txt_GioiTinh.setSelectedItem("Nam");
        txt_Tuoi.setText("");
        txt_SoDienThoai.setText("");
    }
    
    public void bttCapNhatClicked(){
        nv = new NhanVien();
        String maNVstr = txt_MaNhanVien.getText();
        String tenNV = txt_HoVaTen.getText();
        String gioiTinh = (String) txt_GioiTinh.getSelectedItem();
        String tuoi = txt_Tuoi.getText();
        String soDienThoai = txt_SoDienThoai.getText();

        String errorMessage = validateInputValues(maNVstr, tenNV, gioiTinh, tuoi, soDienThoai);
        if (errorMessage != null) {
            JOptionPane.showMessageDialog(rootPane, errorMessage, "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int tuoiNV = Integer.parseInt(tuoi);
        boolean gt = gioiTinh.equals("Nam");

        nv.setMaNV(maNVstr);
        nv.setTenNV(tenNV);
        nv.setGioiTinh(gt);
        nv.setTuoi(tuoiNV);
        nv.setsodienThoai(soDienThoai);

        if(new NhanVienDAO().CapNhatNhanVien(nv)) { // Cập nhật nhân viên thành công
            JOptionPane.showMessageDialog(rootPane, "Cập nhật nhân viên thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            loadTable();
            bttXoaNhapNVClicked();
        } else { // Cập nhật nhân viên không thành công
            JOptionPane.showMessageDialog(rootPane, "Cập nhật nhân viên không thành công!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    
    private void load(){
        btt_CapNhatNhanVien.setEnabled(false);
        btt_XoaNhanVien.setEnabled(false);
        loadTable();
    }
    
    private void loadTable(){
        list = new NhanVienDAO().getListNV();
        DefaultTableModel model = (DefaultTableModel) tbl_NhanVien.getModel();
        model.setRowCount(0);
        int n = list.size()-1;
        for(int i = 0 ; i <= n; i++){
            NhanVien tmp = list.get(i);
            boolean gt = tmp.getGioiTinh();
            String gioiTinh;
            if(gt == true) gioiTinh = "Nam";
            else gioiTinh = "Nữ";
            model.addRow(new Object[]{
                tmp.getMaNV(), tmp.getTenNV(), gioiTinh, tmp.getTuoi(), tmp.getsodienThoai()
            });
        }
        
    }
    
    private void btt_QLSuatAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_QLSuatAnMouseClicked
        new QLSuatAnView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btt_QLSuatAnMouseClicked

    private void btt_QLMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_QLMonAnMouseClicked
        new QLMonAnView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btt_QLMonAnMouseClicked

    private void btt_QLNguyenLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_QLNguyenLieuMouseClicked
        new QLNLView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btt_QLNguyenLieuMouseClicked

    private void txt_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SearchKeyReleased
        String keyword = txt_Search.getText().toLowerCase(); // Lấy giá trị đã nhập và chuyển đổi sang chữ thường
        DefaultTableModel tableModel = (DefaultTableModel) tbl_NhanVien.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tableModel); // Tạo đối tượng RowSorter để sắp xếp và lọc dữ liệu trên bảng
        tbl_NhanVien.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + keyword));// Lọc các hàng trên bảng theo chuỗi tìm kiếm, không phân biệt hoa thường
    }//GEN-LAST:event_txt_SearchKeyReleased
    
    Set<Integer> selectedRows = new HashSet<>();
    Set<Integer> selectedCols = new HashSet<>();
    private void tbl_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NhanVienMouseClicked
        int row = tbl_NhanVien.rowAtPoint(evt.getPoint());
        int col = tbl_NhanVien.columnAtPoint(evt.getPoint());
        
        // Check if the cell is valid and left mouse button is clicked
        if (row >= 0 && col >= 0 && SwingUtilities.isLeftMouseButton(evt)) {
            // If cell is already selected and isSelected is true, then deselect it
            if (selectedRows.contains(row) && selectedCols.contains(col)) {
                tbl_NhanVien.removeRowSelectionInterval(row, row);
                tbl_NhanVien.removeColumnSelectionInterval(col, col);
                selectedRows.remove(row);
                selectedCols.remove(col);
                bttXoaNhapNVClicked();
            } else {
                // Otherwise, select the cell
                tbl_NhanVien.addRowSelectionInterval(row, row);
                tbl_NhanVien.addColumnSelectionInterval(col, col);
                selectedRows.add(row);
                selectedCols.add(col);
            }
        }

    }//GEN-LAST:event_tbl_NhanVienMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_CapNhatNhanVien;
    private javax.swing.JMenu btt_QLMonAn;
    private javax.swing.JMenu btt_QLNguyenLieu;
    private javax.swing.JMenu btt_QLNhanVien;
    private javax.swing.JMenu btt_QLSuatAn;
    private javax.swing.JButton btt_ThemNhanVien;
    private javax.swing.JButton btt_XoaNhanVien;
    private javax.swing.JButton btt_XoaNhapNhanVien;
    private javax.swing.JDialog dialog_ChamCong;
    private javax.swing.JButton dialogbtt_Sua;
    private javax.swing.JButton dialogbtt_TimKiem;
    private javax.swing.JLabel dialoglbl_Luong;
    private javax.swing.JLabel dialoglbl_MaNhanVien;
    private javax.swing.JLabel dialoglbl_NgayCham;
    private javax.swing.JLabel dialoglbl_SoGioLam;
    private javax.swing.JTextField dialogtxt_Luong;
    private javax.swing.JTextField dialogtxt_MaNhanVien;
    private com.toedter.calendar.JDateChooser dialogtxt_NgayCham;
    private javax.swing.JTextField dialogtxt_SoGioLam;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_GioiTinh;
    private javax.swing.JLabel lbl_HoVaTen;
    private javax.swing.JLabel lbl_MaNhanVien;
    private javax.swing.JLabel lbl_SDT;
    private javax.swing.JLabel lbl_Tuoi;
    private javax.swing.JTable tbl_ChamCong;
    private javax.swing.JTable tbl_NhanVien;
    private javax.swing.JComboBox<String> txt_GioiTinh;
    private javax.swing.JTextField txt_HoVaTen;
    private javax.swing.JTextField txt_MaNhanVien;
    private javax.swing.JTextField txt_Search;
    private javax.swing.JTextField txt_SoDienThoai;
    private javax.swing.JTextField txt_Tuoi;
    // End of variables declaration//GEN-END:variables

    
}
