/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ThongKeDAO;
import View.Palette.Model.Model_Card;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author anhtu
 */
public class ThongKeViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeViewPanel
     */
    public ThongKeViewPanel() {
        initComponents();
        tbl_TK_SuatAn.getColumnModel().getColumn(3).setCellRenderer(new DateTimeRenderer());
        loadDatatbl(); 
        loadDataTop_MA();
    }
    
    
    public void loadDatatbl(){
        DefaultTableModel model = (DefaultTableModel) tbl_TK_SuatAn.getModel();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        model.setRowCount(0);
        String startDay = "";
        String endDay = "";
        model = new ThongKeDAO().loadData(model, startDay, endDay);
    }
    
    public void loadDataTop_MA(){
        DefaultTableModel model = (DefaultTableModel) tbl_TK_MonAn.getModel();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        model.setRowCount(0);
        String startDay = "";
        String endDay = "";
        model = new ThongKeDAO().top_MA(model, startDay, endDay);
        
        //load Card
        getDataCard(startDay, endDay);
    }
    
    public void getDataCard(String startDay, String endDay){
        int numSA = new ThongKeDAO().countSA(startDay, endDay);
        int profit = new ThongKeDAO().countTT(startDay, endDay);
        int numMA = new ThongKeDAO().countMA(startDay, endDay);

        String strNumSA = Integer.toString(numSA);
        String strProfit = Integer.toString(profit);
        String strNumMA = Integer.toString(numMA);
        
        card_ProfitTK.setData(new Model_Card(new ImageIcon(getClass().getResource("/ImageIcon/profit.png")), "Tổng Doanh Thu", strProfit, ""));
        card_SATK.setData(new Model_Card(new ImageIcon(getClass().getResource("/ImageIcon/serving-dish.png")), "Tổng Suất Ăn", strNumSA, ""));
        card_MATK.setData(new Model_Card(new ImageIcon(getClass().getResource("/ImageIcon/fish.png")), "Tổng Món Ăn", strNumMA, ""));
    }
    
    public class DateTimeRenderer extends DefaultTableCellRenderer {
        private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    
        // Override phương thức getTableCellRendererComponent() và định dạng lại ngày giờ
        @Override public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            if(value instanceof Date) {
                value = sdf.format((Date) value);
            }
            return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        }
    }
    
    // Sử dụng renderer cho cột chứa giá trị ngày giờ
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        card_ProfitTK = new View.Palette.Card();
        card_SATK = new View.Palette.Card();
        card_MATK = new View.Palette.Card();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_TK_MonAn = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_TK_SuatAn = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_StartDay = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txt_EndDay = new com.toedter.calendar.JDateChooser();
        btt_Search = new javax.swing.JButton();
        btt_BaoCao = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(956, 590));

        card_ProfitTK.setColor1(new java.awt.Color(255, 220, 96));

        card_SATK.setColor1(new java.awt.Color(255, 51, 255));

        card_MATK.setColor1(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(card_ProfitTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(card_SATK, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(card_MATK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card_ProfitTK, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
            .addComponent(card_MATK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(card_SATK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Món Ăn Bán Chạy");

        tbl_TK_MonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Món Ăn", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_TK_MonAn.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbl_TK_MonAn);
        if (tbl_TK_MonAn.getColumnModel().getColumnCount() > 0) {
            tbl_TK_MonAn.getColumnModel().getColumn(0).setResizable(false);
            tbl_TK_MonAn.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        tbl_TK_SuatAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Suất Ăn", "Giá Tiền", "Ngày Lập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_TK_SuatAn.setColumnSelectionAllowed(true);
        tbl_TK_SuatAn.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_TK_SuatAn);
        tbl_TK_SuatAn.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbl_TK_SuatAn.getColumnModel().getColumnCount() > 0) {
            tbl_TK_SuatAn.getColumnModel().getColumn(0).setResizable(false);
            tbl_TK_SuatAn.getColumnModel().getColumn(1).setResizable(false);
            tbl_TK_SuatAn.getColumnModel().getColumn(2).setResizable(false);
            tbl_TK_SuatAn.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setText("Ngày Bắt Đầu");

        jLabel2.setText("Ngày Kết Thúc");

        btt_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/search.png"))); // NOI18N
        btt_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btt_SearchMouseClicked(evt);
            }
        });

        btt_BaoCao.setText("Tạo Báo Cáo");
        btt_BaoCao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btt_BaoCaoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_StartDay, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(txt_EndDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btt_BaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btt_BaoCao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_StartDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_EndDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btt_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_SearchMouseClicked
        DefaultTableModel model = (DefaultTableModel) tbl_TK_SuatAn.getModel();
        DefaultTableModel model2 = (DefaultTableModel) tbl_TK_MonAn.getModel();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        model.setRowCount(0);
        model2.setRowCount(0);
        Date startDate = txt_StartDay.getDate();
        Date endDate = txt_EndDay.getDate();
        if (endDate.compareTo(startDate) < 0) {
            JOptionPane.showMessageDialog(null, "Ngày Bắt Đầu và Kết Thúc Không Hợp Lệ", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String startDay = df.format(startDate);
        String endDay = df.format(endDate);
        model = new ThongKeDAO().loadData(model, startDay, endDay);
        model2 = new ThongKeDAO().top_MA(model2, startDay, endDay);
        getDataCard(startDay, endDay);
    }//GEN-LAST:event_btt_SearchMouseClicked

    private void btt_BaoCaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_BaoCaoMouseClicked
        
    }//GEN-LAST:event_btt_BaoCaoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_BaoCao;
    private javax.swing.JButton btt_Search;
    private View.Palette.Card card_MATK;
    private View.Palette.Card card_ProfitTK;
    private View.Palette.Card card_SATK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_TK_MonAn;
    private javax.swing.JTable tbl_TK_SuatAn;
    private com.toedter.calendar.JDateChooser txt_EndDay;
    private com.toedter.calendar.JDateChooser txt_StartDay;
    // End of variables declaration//GEN-END:variables

    public class DateUtils {
        private static final String DEFAULT_DATE_FORMAT = "yyyy-MM-dd";

        public static Date parseDate(String dateString) throws ParseException {
            return parseDate(dateString, DEFAULT_DATE_FORMAT);
        }

        public static Date parseDate(String dateString, String dateFormat) throws ParseException {
            SimpleDateFormat formatter = new SimpleDateFormat(dateFormat);
            return formatter.parse(dateString);
        }
    }
}
